### ISSUE TITLE
Read.me update with Functional component and React Hooks

### ISSUE THREAD

**Issue by felipexperto** [deckgo/gatsby-remark-highlight-code#2]
Hi David. First of all, nice job! 👏 
Just one little thing, I think an example using functional components and hooks would be useful. 
Something like this:

#### Class component

```javascript
async componentDidMount() {
    try {
        const deckdeckgoHighlightCodeLoader = require("@deckdeckgo/highlight-code/dist/loader")
    
        await deckdeckgoHighlightCodeLoader.defineCustomElements(window);
    } catch (err) {
        console.error(err);
    }
}
```  

#### Functional component with hooks

```javascript
import React, { Fragment, useEffect } from "react";
import { defineCustomElements as deckdeckgoLoader} from '@deckdeckgo/highlight-code/dist/loader';

const yourComponent = () => {

  useEffect(() => {
    try {
      deckdeckgoLoader(window);
    } catch (err) {
      console.log(err);
    }
  },[]);

  return (
    <Fragment>
      <ComponentOne />
      <ComponentTwo />
      [...]
    </Fragment>
  )
}

export default yourComponent;
```

What do you think about it?

**Comment by peterpeterparker** [comment]
Thank you @felipexperto it's a great idea!

I would suggest that we wait a bit before integrating it because the related Stencil issue [#1724](https://github.com/ionic-team/stencil/issues/1724) as actually been solved and will be delivered in v1.9.

Therefore, once I'll upgrade the component it's good possible that this workaround won't be necessary anymore and that it will be possible to load it the same way for both class or functional component.

I'll keep a good eye on it!

**Comment by felipexperto** [comment]
Nice! I'm looking forward to it!
Based on that, I'm gonna close this issue, ok?
Thank you :)

**Comment by peterpeterparker** [comment]
Sure cool, thx @felipexperto 

I'm a bit behind schedule because I want to finish a big PR for our editor but I hope to be able to try out Stencil v1.9 asap.

**Comment by peterpeterparker** [comment]
Thank you @felipexperto, I have added your example to the README as Stencil >= v1.9 doesn't seems to solve the problem aka the workaround is still needed.

**Comment by peterpeterparker** [comment]
Ahah it turned out that it was actually solved ;)

I have now updated the README file, no workaround needed anymore.
