### ISSUE TITLE
Feature Request: Ability to remove the 3 dots in the window

### ISSUE THREAD

**Issue by jer-k** [deckgo/gatsby-remark-highlight-code#21]
On the Carbon generator (https://carbon.now.sh/) it is possible to remove the 3 dots using in the Settings -> Window -> Window Controls to produce this type of output 

![carbon](https://user-images.githubusercontent.com/1280586/93262246-c1461600-f758-11ea-9926-ca0d5204c9b2.png)

From what I could tell, this functionality is not available unless you use `terminal: 'none'` which leads to the theme not being used. Would it be possible to add the functionality to use `terminal: 'carbon'` but remove the 3 dots?

**Comment by peterpeterparker** [comment]
I think it would be possible to add the functionality, thank you for the idea 👍.

It would have to be implemented in the [@deckdeckgo/highlight-code](https://github.com/deckgo/deckdeckgo/tree/master/webcomponents/highlight-code) Web Component.

Instead of an option, I would rather use CSS4 variable, as for example adding and using a CSS variable `--deckgo-highlight-code-carbon-toolbar-display` which can be set  to `none`. 

I rather to modify the style through CSS than Properties when possible.

If you or anyone can provide a PR, happy to have a look and merge it.

**Comment by peterpeterparker** [comment]
Awesome @jer-k !

It has been released. Both this plugin and the web component in version v2.1.0. 

Let me know if there is something more to do.

Thx 🙏
