### ISSUE TITLE
Support for highlightLines attribute

### ISSUE THREAD

**Issue by AhsanAyaz** [deckgo/gatsby-remark-highlight-code#28]
The deckdeckgo `code` component allows highlighting certain lines.
Adding the support in this package would be awesome!
https://docs.deckdeckgo.com/components/code/#app-components-highlight-code-examples

**Comment by peterpeterparker** [comment]
Sure good idea,  we should add `highlightLines` to the list of [pluginOptions](https://github.com/deckgo/gatsby-remark-highlight-code/blob/b6ae63b7820a776632d109ae077a3b4438546ee3/index.js#L32)

**Comment by peterpeterparker** [comment]
I checked again but, I see an issue. The `pluginOptions` are global for the site. To the contrary, `highlightLines` is probably something you want to use on a particular piece of code of the website (like this code lines 1 to 3, that one 5 to 8).

Not sure how we should solve this, any idea ?

**Comment by AhsanAyaz** [comment]
Yeah 😄 
If it was just adding the `pluginOption`, you'd already have a PR from me 😄 .
I guess we'll have to think it through on how to do this. I'm gonna spend some time looking at this. Feel free to share any ideas that you get as well.

**Comment by peterpeterparker** [comment]
Thanks for having a look, that would be really nice 😃.

Spontaneously  I am thinking that instead of property/attributes maybe it can be solved  with CSS4 variables. The component would had to be modified to read these  but, it would allow users to specify lines even when using the plugin. Not sure it would work and there are probably better solutions. Looking forward to your ideas!

**Comment by AhsanAyaz** [comment]
@peterpeterparker I did something ☝️ 🙂 
The applies the attribute's value correctly to the `<deckgo-highlight-code>` properly. However, the deckgo-highlight-code component itself doesn't work fine with it for some reason. See the image attached:
<img width="861" alt="Screenshot 2021-02-16 at 20 30 55" src="https://user-images.githubusercontent.com/9844254/108112810-e7b90600-7096-11eb-96f6-c86327388708.png">

**Comment by peterpeterparker** [comment]
thx for the PR @AhsanAyaz 🙏

it doesn't highlight lines because of the format. instead of `4 7, 20 35` it should parse `4,5 20,35`, the coma being the separate for "from,to" and the space being the separator between "group".

would you like to give a try and let me know if it works out?

cool idea and solution 👍

**Comment by AhsanAyaz** [comment]
Ah 😲 ! Now I got it.
Sure. Will implement the correct format and will update the PR.

**Comment by peterpeterparker** [comment]
Awesome! keep me posted and let me know if I can do anything.

**Comment by AhsanAyaz** [comment]
Just pushed the code to the PR with the right format and fixed tests.
Seems cool now:
![image](https://user-images.githubusercontent.com/9844254/108127584-bbf44b00-70ab-11eb-994a-a42db23dde52.png)

**Comment by peterpeterparker** [comment]
Sweet, looks good!

I'll test the PR with my website tomorrow after work. If all good (I have no doubt, looks cool), merge and release afterwards.

I keep you posted, good night.
