### ISSUE TITLE
Hide the colored balls in Carbon theme

### ISSUE THREAD

**Issue by kaphula** [deckgo/gatsby-remark-highlight-code#41]
Hey, is it possible to hide the colored balls on Carbon theme? I'd like to keep the card background but without the colored balls that appear on top of each listing. Or alternatively, can you turn the background on for None theme?

**Comment by peterpeterparker** [comment]
Sure, I do that on my [website](https://daviddalbusco.com) too. 

The CSS variable `--deckgo-highlight-code-carbon-toolbar-display: none;` is probably the one you are looking for otherwise there are quite some styling options listed in the [doc](https://docs.deckdeckgo.com/?path=/docs/components-highlight-code--highlight-code).
