### ISSUE TITLE
Rerendering deckgo-highlight-code compontent on state change

### ISSUE THREAD

**Issue by piorus** [deckgo/gatsby-remark-highlight-code#58]
I spent a few hours yesterday trying to figure out how to re-render `deckgo-highlight-code` component when the state changes with no success.

this:

```jsx
import React from 'react';

import {defineCustomElements as highlightCodeElements} from '@deckdeckgo/highlight-code/dist/loader';
highlightCodeElements();

export const CustomComponent = ({ modelName, ...props }) => {
    return <>
        {modelName}
        <deckgo-highlight-code language="php">
            <code slot="code">echo "{modelName}";</code>
        </deckgo-highlight-code>
    </>
};
```

Just plain does not work. When `modelName` changes, highlighted code stays the same.

### initial load
![](https://i.imgur.com/HnsWebs.png)

### when modelName changes
![](https://i.imgur.com/mTCqjPN.png)

**Comment by peterpeterparker** [comment]
I am guessing that in your case the component remains in the dom and only its slotted content change but, the component does not reload if on slot changes currently that's why I assume it is not reloaded.

So, have you try to reload it using the function `load`? 

> Methods
>load() => Promise<void>
>
>Load or reload the component

In JS: `await document.querySelector('deckgo-higlight-code').load()`

**Comment by piorus** [comment]
@peterpeterparker yes, only slotted content changed. It's working now with querySelector & load(). thank you

**Comment by peterpeterparker** [comment]
Super, thanks for the feedback
